site_name: scramblery
site_url: https://github.com/altunenes/scramblery
nav:
  - Home: index.md
  - User Guide: userguide.md
  - API: api_reference.md
  - demo: scramblerydemo.html
  - animation: magic.html
  - animation2: pixeldance.html

theme: readthedocs