[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
rayon = "1.10.0"
image = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
face_detection = { path = "../face_detection" }