[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
image = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }