name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: '--target aarch64-apple-darwin'
          - platform: macos-latest
            args: '--target x86_64-apple-darwin'
          - platform: ubuntu-22.04
            args: ''
          - platform: windows-latest
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './ui/package-lock.json'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Setup GStreamer
        uses: blinemedical/setup-gstreamer@1.0
        with:
          version: '1.22.8'
          arch: 'x86_64'

      # Linux dependencies
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libunwind-dev \
            build-essential \
            libglib2.0-dev

      # macOS dependencies
      - name: Install macOS dependencies
        if: matrix.platform == 'macos-latest'
        run: |
          brew install pkg-config glib

      # Fix paths for Windows
      - name: Setup Windows environment
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          echo "PKG_CONFIG_PATH=$env:GSTREAMER_1_0_ROOT_MSVC_X86_64\lib\pkgconfig" >> $env:GITHUB_ENV
          echo "GSTREAMER_1_0_ROOT_MSVC_X86_64=$env:GSTREAMER_1_0_ROOT_MSVC_X86_64" >> $env:GITHUB_ENV
          echo "PATH=$env:GSTREAMER_1_0_ROOT_MSVC_X86_64\bin;$env:PATH" >> $env:GITHUB_ENV

      - name: Install frontend dependencies
        run: |
          cd ui
          npm install

      - name: Setup workspace
        run: |
          echo "Checking workspace structure..."
          ls -la
          echo "Contents of engine directory:"
          ls -la engine || echo "engine directory not found"
          echo "Contents of Cargo.toml:"
          cat Cargo.toml || echo "Cargo.toml not found"

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_ALLOW_CROSS: 1
        with:
          projectPath: './ui'
          tagName: ${{ github.ref_name }}
          releaseName: 'Scramblery ${{ github.ref_name }}'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}