name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: '--target aarch64-apple-darwin'
          - platform: macos-latest
            args: '--target x86_64-apple-darwin'
          - platform: ubuntu-22.04
            args: ''
          - platform: windows-latest
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix workspace path
        shell: bash
        run: |
          pwd
          ls -la
          # Create symbolic links if engine is in a different location
          if [ ! -d "engine" ] && [ -d "../engine" ]; then
            ln -s ../engine engine
          fi
          # Show workspace structure
          echo "Current directory structure:"
          ls -la
          echo "Cargo.toml contents:"
          cat Cargo.toml

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './ui/package-lock.json'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      # Linux dependencies
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libunwind-dev \
            pkg-config \
            cmake \
            build-essential \
            libglib2.0-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly

      # macOS dependencies
      - name: Install macOS dependencies
        if: matrix.platform == 'macos-latest'
        run: |
          brew install pkg-config glib gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly
          
          # Set GStreamer environment variables
          BREW_PREFIX=$(brew --prefix)
          GST_PREFIX="$BREW_PREFIX/opt/gstreamer"
          
          # Create pkgconfig directory if it doesn't exist
          sudo mkdir -p /usr/local/lib/pkgconfig
          
          # Set environment variables
          echo "PKG_CONFIG_PATH=$BREW_PREFIX/lib/pkgconfig:$GST_PREFIX/lib/pkgconfig:/usr/local/lib/pkgconfig" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$BREW_PREFIX/lib:/usr/local/lib" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=$BREW_PREFIX/lib:/usr/local/lib" >> $GITHUB_ENV
          echo "GST_PLUGIN_PATH=$BREW_PREFIX/lib/gstreamer-1.0" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          
          # Debug information
          ls -la $BREW_PREFIX/lib/pkgconfig
          pkg-config --list-all | grep gstreamer
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"

      # Windows dependencies
      - name: Install Windows dependencies
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          # Install pkg-config
          choco install -y pkgconfiglite
          
          # Download GStreamer
          $gstVer = "1.22.8"
          $gstUrl = "https://gstreamer.freedesktop.org/data/pkg/windows/$gstVer/msvc"
          
          Write-Host "Downloading GStreamer..."
          Invoke-WebRequest -Uri "$gstUrl/gstreamer-1.0-msvc-x86_64-$gstVer.msi" -OutFile "gstreamer.msi"
          Invoke-WebRequest -Uri "$gstUrl/gstreamer-1.0-devel-msvc-x86_64-$gstVer.msi" -OutFile "gstreamer-devel.msi"
          
          Write-Host "Installing GStreamer..."
          Start-Process msiexec.exe -Wait -ArgumentList "/i gstreamer.msi /quiet /qn /norestart ADDLOCAL=CompleteInstall"
          Start-Process msiexec.exe -Wait -ArgumentList "/i gstreamer-devel.msi /quiet /qn /norestart ADDLOCAL=CompleteInstall"
          
          $gstRoot = "C:\gstreamer\1.0\msvc_x86_64"
          
          Write-Host "Setting environment variables..."
          echo "GSTREAMER_1_0_ROOT_MSVC_X86_64=$gstRoot" >> $env:GITHUB_ENV
          echo "PKG_CONFIG_PATH=$gstRoot\lib\pkgconfig" >> $env:GITHUB_ENV
          echo "PATH=$gstRoot\bin;$env:PATH" >> $env:GITHUB_ENV
          
          # Verify installation
          Write-Host "Verifying installation..."
          $env:PATH = "$gstRoot\bin;$env:PATH"
          Get-ChildItem "$gstRoot\bin"
          
          if (Test-Path "$gstRoot\bin\gst-launch-1.0.exe") {
              Write-Host "GStreamer installation verified"
          } else {
              Write-Host "GStreamer installation failed"
              exit 1
          }

      - name: Install frontend dependencies
        run: |
          cd ui
          npm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_ALLOW_CROSS: 1
        with:
          projectPath: './ui'
          tagName: ${{ github.ref_name }}
          releaseName: 'Scramblery ${{ github.ref_name }}'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}