#based on the: https://github.com/tauri-apps/tauri-action
name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: '--target aarch64-apple-darwin'
          - platform: macos-latest
            args: '--target x86_64-apple-darwin'
          - platform: ubuntu-22.04
            args: ''
          - platform: windows-latest
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './ui/package-lock.json'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      # Linux dependencies
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libunwind-dev \
            pkg-config \
            cmake \
            build-essential \
            libglib2.0-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly

      # macOS dependencies
      - name: Install macOS dependencies
        if: matrix.platform == 'macos-latest'
        run: |
          brew install pkg-config glib gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly
          echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/homebrew/lib/pkgconfig:/opt/homebrew/Cellar/gstreamer/1.22.8/lib/pkgconfig" >> $GITHUB_ENV
          echo "LIBRARY_PATH=/usr/local/lib:/opt/homebrew/lib:/opt/homebrew/Cellar/gstreamer/1.22.8/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=/opt/homebrew/lib:/opt/homebrew/Cellar/gstreamer/1.22.8/lib" >> $GITHUB_ENV
          echo "GST_PLUGIN_PATH=/opt/homebrew/lib/gstreamer-1.0" >> $GITHUB_ENV

      # Windows dependencies
      - name: Install Windows dependencies
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          choco install -y pkgconfiglite
          choco install -y mingw
          
          # Download and extract GStreamer development and runtime installers
          Invoke-WebRequest -Uri "https://gstreamer.freedesktop.org/data/pkg/windows/1.22.8/msvc/gstreamer-1.0-msvc-x86_64-1.22.8.msi" -OutFile "gstreamer.msi"
          Invoke-WebRequest -Uri "https://gstreamer.freedesktop.org/data/pkg/windows/1.22.8/msvc/gstreamer-1.0-devel-msvc-x86_64-1.22.8.msi" -OutFile "gstreamer-devel.msi"
          
          # Install MSIs
          Start-Process -Wait msiexec -ArgumentList "/i gstreamer.msi /quiet"
          Start-Process -Wait msiexec -ArgumentList "/i gstreamer-devel.msi /quiet"
          
          # Set environment variables
          echo "PKG_CONFIG_PATH=C:\gstreamer\1.0\msvc_x86_64\lib\pkgconfig" >> $env:GITHUB_ENV
          echo "GSTREAMER_1_0_ROOT_MSVC_X86_64=C:\gstreamer\1.0\msvc_x86_64" >> $env:GITHUB_ENV
          echo "PATH=C:\gstreamer\1.0\msvc_x86_64\bin;$env:PATH" >> $env:GITHUB_ENV

      - name: Install frontend dependencies
        run: |
          cd ui
          npm install

      - name: Check environment
        run: |
          pkg-config --version || echo "pkg-config not found"
          pkg-config --list-all || echo "No packages found"
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
          
      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_ALLOW_CROSS: 1
        with:
          projectPath: './ui'
          tagName: ${{ github.ref_name }}
          releaseName: 'Scramblery ${{ github.ref_name }}'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}